# Mergify configuration for automatic PR merging

pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - "check-success=say-hello-workflow"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        strict: false
