# Mergify config revalidation

pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - "status-success=ci/circleci: build"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        strict: false
